CREATE DATABASE IF NOT EXISTS dev;
USE dev;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS news (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    text TEXT NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

INSERT INTO news (name, text) VALUES
                                      ('News 1', 'It is news number 1. Lacinia sed risus aenean sodales ipsum molestie accumsan pulvinar in arcu nisi nec accumsan urna dictum. Adipiscing accumsan adipiscing amet, hac vestibulum est. Aenean in integer venenatis accumsan in justo ut. Dictumst. Molestie sit malesuada venenatis pulvinar ut. Nec cursus dui vitae nisi non est. Vitae mauris mattis ornare dolor arcu vel tortor, nulla cursus pellentesque urna ipsum mattis habitasse pulvinar quam, dolor risus non faucibus. Aenean integer molestie urna dictum. Odio. Vestibulum velit velit vulputate nec pulvinar arcu vulputate id et eleifend ornare tortor, efficitur et nisi cursus nec sodales malesuada dictum eget tortor, vel ipsum sed habitasse ex. Molestie mollis lacinia non et ornare justo lacinia faucibus. Eleifend mauris ut. Lacinia malesuada pulvinar elit. Vitae odio. Pellentesque vestibulum sodales integer ornare ornare adipiscing sapien libero, faucibus. Platea ornare et. Ipsum eleifend non vestibulum est. Cursus dolor odio. Mollis eleifend elit. Molestie imperdiet vulputate platea lacinia et amet, lectus sit integer justo lorem ipsum nisi vel id cras et arcu sapien vulputate cras nec risus tempus interdum est. In quam, nec sit amet hac quam, vel tortor, vulputate augue lectus pellentesque luctus vulputate risus ornare risus molestie ornare pulvinar dictum dictum vel sodales platea ex. Tempus leo, eleifend ne.'),
                                      ('News 2', 'It is news number 2. Id pulvinar faucibus. Mattis risus quis, dictum augue leo, ex. Amet, et et lorem ipsum orci, eget sed et venenatis sed sed sapien in sed cursus ex. Adipiscing nunc mauris et. Quam, interdum quam, nec amet, amet, ipsum justo sed imperdiet orci, et amet luctus sed mattis in luctus in ornare sit in pulvinar ut. Sed lacinia venenatis hac ornare dictumst. Et cras sed quam, sit nec quis, faucibus. Integer et odio. Lorem malesuada molestie dictum. Tempus est. Quis, augue odio. Tempus pulvinar justo venenatis nisi imperdiet interdum venenatis nisi venenatis est. In mattis elit. Amet sed malesuada hac hac ut. Dolor ex. Mattis interdum ut. In eleifend non nisi nisi sed imperdiet lorem accumsan libero, pellentesque eleifend et. Sed quis, dolor non tortor, mattis lorem orci, risus luctus morbi ex. Nulla nec in et lacinia eleifend luctus cras dictum. Vel integer consectetur consectetur sit pulvinar tortor, ex. Sit sapien efficitur mauris amet, augue efficitur leo, sit ex. Sit cursus lacinia libero, consectetur ultricies. Vulputate morbi urna et nunc risus non ultricies. Eget in dui amet, tortor, dictum ex. Quis, tortor, arcu sit amet, sit efficitur elit. Urna pellentesque dui mattis sodales eget nunc tortor, efficitur morbi quam, pulvinar no.'),
                                      ('News 3', 'It is news number 3. Non non lacinia justo amet libero, vel platea amet mauris molestie ultricies. Vestibulum efficitur sodales vestibulum ex. Molestie lectus in vitae eleifend cursus lacinia ipsum nisi mattis in sed accumsan arcu cras tempus morbi et. Dui arcu molestie et arcu nisi dui non dapibus ut. In justo et. Consectetur mollis velit luctus sodales non libero, quam, molestie urna cursus leo, libero, pulvinar non non sed tortor, urna consectetur dui dictum. Sit pellentesque integer amet, sapien nulla tempus vestibulum morbi ex. Molestie consectetur non interdum pulvinar malesuada cursus in quam, in non ipsum quis, id nisi consectetur quam, pellentesque consectetur elit. Ornare ut. Ut. In et quam, ipsum lorem ipsum non vel amet id lectus dictum. Et libero, venenatis nisi amet ex. Elit. Nunc adipiscing vulputate molestie amet, in platea justo ultricies. Dictumst. Adipiscing ipsum urna in in vulputate dolor in leo, risus non lorem non est. Augue dictum. Venenatis lectus et. Arcu dictum. Augue vitae pulvinar dictum in odio. Sit elit. Sit nulla orci, tortor, amet, nec nunc efficitur luctus ex. Quam, integer molestie in nulla ornare interdum morbi vestibulum et ultricies. Quam, pellentesque malesuada dolor eget ornare pellentesque lorem nunc non dictum dictumst. Odio. Imperdiet odio. Leo, dui lacinia ipsum et. Et justo dui dictumst. Sit amet et mauris et. Mollis cursus venenatis hac non mattis nulla quam, velit id quis, urna lacinia sit morbi luctus arcu consectetur et. Sit non pellentesque dictum. Et. Consectetur est. Quis, id mauris imperdiet molestie cras tortor, amet lectus mollis risus arcu quam, vitae platea urna urna et. Vitae vitae amet, sit urna ultricies. Interdum mollis eleifend adipiscing accumsan dolor sodales hac pellentesque augue velit dui dictum eleifend quis, venenatis tempus hac dui dapibus molestie quam, habitasse mauris dui cras molestie luctus ex. Platea sit non libero, interdum dui et sed consectetur no.'),
                                      ('News 4', 'It is news number 4. Leo, efficitur et. Adipiscing libero, arcu ex. Mollis in in dapibus ornare faucibus. Sed nisi libero, tempus mattis luctus ipsum est. Quam, dictum. Et. In sit amet molestie consectetur sapien morbi urna vitae dictumst. Imperdiet nulla quis, non luctus sed morbi sed dapibus non dictum. Ut. Quis, luctus ut. Lectus adipiscing tortor, id sed ornare cras adipiscing ultricies. Non odio. Quam, in vulputate dictum non ornare in eleifend ut. Amet, molestie et. Urna ut. Molestie cursus dapibus nisi quam, vel dapibus amet, dictumst. Aenean dictum lacinia odio. Quam, integer malesuada hac dapibus sodales orci, interdum lacinia nec nunc dolor si.'),
                                      ('News 5', 'It is news number 5. Sed adipiscing in sit platea dictum. Interdum in faucibus. Sodales mauris amet non mauris platea accumsan sed velit sapien venenatis vestibulum velit nulla aenean tempus pellentesque sed nunc imperdiet dui nisi vulputate sit quis, amet, justo orci, adipiscing ornare eget ornare ex. Odio. Id venenatis non tortor, elit. Ornare hac in sed imperdiet amet non hac vel malesuada tempus justo nulla mollis amet, in non amet leo, molestie pellentesque augue mattis ipsum pellentesque dictum. Quam, habitasse imperdiet amet non lacinia lacinia accumsan urna ut. Molestie id nec interdum est. Sed et sed non justo ornare amet, sed ornare molestie ha.');